### PR TITLE
[Benchmark] Add binary search

### PR DESCRIPTION
**Pull request by yy665**
A not-very-interesting binary search implementation.

### CODE REVIEW

**Review by sampsyo — CHANGES_REQUESTED** [review]
Looks like a good start! The tests seem to be failing, probably because of a missing newline on the `.out` and `.prof` output files. Can you try using `turnt --save` to update those and see if that fixes it?

**Comment by sampsyo** [comment]
Hi, @yy665—just a reminder that this needs a second look!

**Comment by yy665** [comment]
> Hi, @yy665—just a reminder that this needs a second look!

Sorry, I just saw the notification. I have pushed the fix.

**Comment by sampsyo** [comment]
Hmm; looks like there are now *two* newlines at the ends of both files? Using `turnt --save` could bypass this trouble, as opposed to manually editing the files…

**Review by sampsyo — APPROVED** [review]
Looks like everything's green now!

**Pull request merged**
