### PR TITLE
Expose the C runtime library to Rust library users

### PR DESCRIPTION
**Pull request by Alex-Fischman**
Adds a `c_runtime` function.

### CODE REVIEW

**Comment by sampsyo** [comment]
Ah, looks interesting! I can see potentially how this would be useful—any chance you could write a few sentences about the use case and why it's helpful to have this embedded in the library/executable instead of on the filesystem?

One somewhat annoying thing: the path `../rt.c` depends on the directory where `rustc` is run. It will run into problems when, for example, doing [cargo publish](https://github.com/rust-lang/cargo/issues/13309). I think the solution is to use the `$CARGO_MANIFEST_DIR` environment variable, which Cargo sets to the appropriate path. [This SO answer](https://stackoverflow.com/a/68865971) suggests one possible way, for instance. Can you give that a try and see if it works the way you expect?

**Comment by Alex-Fischman** [comment]
This is useful because the alternative for library users is to go into this repo, download the file, and then move it into their repository. However, this will fail if this repo ever changes `rt.c`, because the local copy will not match. This is reasonably likely to happen in the future, for example if `char` becomes supported `rt.c` will need to add `_bril_print_char`.

**Comment by Alex-Fischman** [comment]
It's also useful as a way to remind maintainers that `rt.c` is a necessary part of the API for `brilift`.

**Comment by Pat-Lafon** [comment]
> This is useful because the alternative for library users is to go into this repo, download the file, and then move it into their repository. However, this will fail if this repo ever changes `rt.c`, because the local copy will not match. This is reasonably likely to happen in the future, for example if `char` becomes supported `rt.c` will need to add `_bril_print_char`.

Maybe not the best solution but if you include bril as a git-submodule and then add it via a path versus having cargo look at git directly, you can have a symlink to `rt.c` in your repository. It also exists at a deterministic location on your machine in `$HOME/.cargo/` though maybe that is a little less clean

**Pull request merged**
