### PR TITLE
Make division by zero an error in brilirs

### PR DESCRIPTION
**Pull request by Pat-Lafon**
See #139

### CODE REVIEW

**Comment by sampsyo** [comment]
Seems like a good idea to me, overall! I assume the test is failing because `brili` just returns `Infinity` or whatever? Maybe we should change it too to match…

**Comment by Pat-Lafon** [comment]
The test currently fails because `brili` just executes the division by zero and doesn't gracefully handle the js `RangeError: Division by zero`. Based on the #139 discussion I see that this is allowable behavior, though probably not ideal for the reference interpreter.

Given this, should I move the test case to something like `test/brilirs-error/`?

> I assume the test is failing because brili just returns Infinity or whatever? Maybe we should change it too to match…

2ed5d33 Handled the mismatch on `Infinity`.

**Comment by sampsyo** [comment]
Ah, neat! Here's another approach: I just fixed `brili` to exit gracefully with an error.

I didn't realize that, while `/` on plain old *numbers* in JavaScript returns a value without an error, doing it on `BigInt` objects raises an error. That's good! Anyway, we now detect this situation and raise our own error instead.

**Comment by Pat-Lafon** [comment]
Works for me and looks like everything now passes.

**Comment by sampsyo** [comment]
Awesome!

**Pull request merged**
