### PR TITLE
add incredibly naive pythagorean triple finder

### PR DESCRIPTION
**Pull request by Calsign**

### CODE REVIEW

**Comment by sampsyo** [comment]
This is a good start! As the task description says, can you please add to the docs and include the test output?

**Review by sampsyo — CHANGES_REQUESTED** [review]
This is a good start! As the task description says, can you please add to the docs and include the test output?

**Comment by Calsign** [comment]
Should be better now, sorry about that

**Comment by sampsyo** [comment]
Looks good; thanks!!

**Pull request merged**
